### ISSUE TITLE
transport_model() intermediate folder

### ISSUE THREAD

**Issue by Joaobazzo** [ipeaGIT/gtfs2emis#95]
use the intermediate output of gps_fix_speed

**Comment by rafapereirabr** [comment]
Bazzo, could you please explain a bit better what do you mean with this issue ? Explaning the issue is important for future documentation. I've 'suffered' before in other packages for opening issues without proper explanations lol

**Comment by Joaobazzo** [comment]
The issue is related to the folder `outputfile_path` in [line 68](https://github.com/ipeaGIT/gtfs2emis/blob/master/R/transport_model.R#L198) of `transport_model()`. The function only creates the `outputfile_path` directory if the condition of `continue == TRUE` is satisfied. However, the command `dir.create(outputfile_path)` needs to be executed regardless this condition.
