### ISSUE TITLE
Units of pollutant in MOVES3/EPA

### ISSUE THREAD

**Issue by CANADATA-01** [ipeaGIT/gtfs2emis#96]
What is the SI unit(kg/km, kj/km, etc) for pollutants in MOVES3/EPA data?

**Comment by Joaobazzo** [comment]
Hi @CANADATA-01 
The units are in [g/km]. You can check all MOVES/EPA available emission factor using this code below 

```r
library(gtfs2emis)

data("ef_usa_moves_db")
ef_usa_moves_db

```

**Comment by rafapereirabr** [comment]
Perhaps we should add a coulum "units" to the `data("ef_usa_moves_db")` data set to clarify the measurment unit used for each pollutant

**Comment by Joaobazzo** [comment]
The EF column has units class, so users can check.
```r
> head(ef_usa_moves_db,2)
   fuel_type reference_year model_year pollutant lower_speed_interval upper_speed_interval
1:       CNG           2015       1989       CH4             0 [km/h]           4.0 [km/h]
2:       CNG           2015       1989       CH4             4 [km/h]          12.1 [km/h]
                ef source_type id_speed
1: 69.12351 [g/km] Transit Bus        1
2: 41.04421 [g/km] Transit Bus        2
```
We can add an extra column for the units, but I believe this will be only necessary when we increase the EF database by adding newer units (e.g. [g/kWh or # /kWh] )

**Comment by CANADATA-01** [comment]
Resolved. Thank you @rafapereirabr & @Joaobazzo for the help!
